[mypy]
# Ignoruj błędy o brakujących stubach (typach) dla zewnętrznych bibliotek jak Django czy DRF
ignore_missing_imports = True

# Opcjonalnie: wyklucz folder środowiska wirtualnego i migracje ze sprawdzania
exclude = (?x)(
    ^venv/
    | ^env/
    | migrations/
  )