# Generated by Django 6.0.4 on 2026-05-09 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Kod ISO waluty (np. PLN, USD, EUR)', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(help_text='Symbol waluty (np. zł, $, €)', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('INCOME', 'Przychód'), ('EXPENSE', 'Wydatek')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Ile użytkownik ma obecnie kasy', max_digits=12)),
                ('pending_expenses', models.DecimalField(decimal_places=2, default=0.0, help_text='Suma zaplanowanych wydatków w tym miesiącu', max_digits=12)),
                ('free_funds', models.DecimalField(decimal_places=2, default=0.0, help_text='Wolne środki (np. balans - wydatki)', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INCOME', 'Przychód'), ('EXPENSE', 'Wydatek')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_realized', models.BooleanField(default=True, help_text='Czy transakcja już się odbyła?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='finances.category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finances.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INCOME', 'Przychód'), ('EXPENSE', 'Wydatek')], max_length=10)),
                ('frequency', models.CharField(choices=[('DAILY', 'Codziennie'), ('WEEKLY', 'Co tydzień'), ('MONTHLY', 'Co miesiąc'), ('YEARLY', 'Co rok')], default='MONTHLY', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Pozostaw puste dla nieskończonych subskrypcji', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_plans', to='finances.category')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_plans', to='finances.wallet')),
            ],
        ),
    ]
