name: BE - Portfel+

on:
  push:
    branches: [ "**" ]
    paths:
      - 'apps/backend/**'
  pull_request:
    paths:
      - 'apps/backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check src

  type_check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Mypy and dependencies
        run: |
          pip install mypy
          pip install -r requirements.txt 

      - name: Run Mypy
        run: mypy src --config-file mypy.ini

  build_and_publish:
    needs: [lint, type_check]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/backend
          file: ./apps/backend/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfel-repo/portfel-backend:latest