name: FE - Portfel+

on:
  push:
    branches: [ "**" ]
    paths:
      - 'apps/frontend/**'
  pull_request:
    paths:
      - 'apps/frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  build_and_publish:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Logowanie do Google Cloud
      - name: Authenticate to Google Cloud
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 2. Konfiguracja Dockera pod Google Artifact Registry
      - name: Configure Docker for GCP
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

      # 3. Budowanie i wypychanie do GCP
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./apps/frontend
          file: ./apps/frontend/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          # Tag celujący prosto do Twojego Artifact Registry
          tags: europe-central2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/portfel-repo/portfel-frontend:latest